### ISSUE TITLE
fix: Cast string to Boolean

### ISSUE THREAD

**Issue by QuanticPotatoes** [typestack/class-transformer#626] opened 2021-03-04 14:15 UTC
Hi, I use class-transformer on NestJS and a cast problem occured during the conversion of the request payload.

Example :
```json
{
"page": "1",
"limit": "1",
"isAnnotate": "false"
}
```
We got : 
```js
{
page: 1,
limit: 1,
isAnnotate: true
}
```

The defining class is : 
```ts
class ArticleQuery {
  page: number;

  limit: number;

  isAnnotate?: boolean
}
```

https://github.com/nestjs/nest/blob/master/packages/common/pipes/validation.pipe.ts#L96
When the `plainToClass` function was executed such as : 
```ts
/*
* metatype => ArticleQuery
* value => { page: "1", limit: "1",  isAnnotate: "false" }
* transformOptions => { enableImplicitConversion: true }
* /
classTransformer.plainToClass(metatype, value, this.transformOptions);
```

After a little digging, i found the caused into the function `transform` :
https://github.com/typestack/class-transformer/blob/develop/src/TransformOperationExecutor.ts#L108

```ts
    } else if (targetType === Boolean && !isMap) {
      if (value === null || value === undefined) return value;
      return Boolean(value);
```

So i made a patch locally to solve the issue : 
```ts
    } else if (targetType === Boolean && !isMap) {
      if (value === null || value === undefined) return value;
      return value === "true";
```

Is it an attended behavior from the function to not convert a string "true"/"false" to a Boolean ?

Current version: 0.4.0

Best regards

**Comment by tferi99** [comment] 2021-03-12 23:30
@QuanticPotatoes - will this fix committed into next official version?

**Comment by tferi99** [comment] 2021-03-12 23:31
@QuanticPotatoes - will this fix committed into next official version?

**Comment by skrosoft** [comment] 2021-03-23 00:31
"false" is true ... In my opinion, this should not be casted, correct type or use a transform annotation should be used.

    @Transform(({ obj }) => {
        return [true, 'enabled', 'true'].indexOf(obj.isAnnotate) > -1;
    })

**Comment by felinto-dev** [comment] 2021-03-28 14:26
> "false" is true ... In my opinion, this should not be casted, correct type or transform annotation should be used.
> 
> ```
> @Transform(({ obj }) => {
>     return [true, 'enabled', 'true'].indexOf(obj.isAnnotate) > -1;
> })
> ```

Good Job!

I was looking for it! Is there any way to return an error if no "true" or "false" was sent?
I think to accept any value (that not be true) as false is weird.

Other way could be use with class-validator:

```
  @Transform(({ value }) => {
    return [true, 'enabled', 'true'].indexOf(value) > -1;
  })
  @IsBooleanString()
  isUnlocked: boolean;
```

but just does not work for me and I don't have any idea about what is happening

**Comment by jacobdo2** [comment] 2021-05-11 13:35
> "false" is true ... In my opinion, this should not be casted, correct type or transform annotation should be used.
> 
> ```
> @Transform(({ obj }) => {
>     return [true, 'enabled', 'true'].indexOf(obj.isAnnotate) > -1;
> })
> ```

Your statement is "false"

**Comment by aenkas** [comment] 2021-10-05 08:44
> @Transform(({ value }) => {
>     return [true, 'enabled', 'true'].indexOf(value) > -1;
>   })
>   @IsBooleanString()

After transforming value is boolean, not boolean-string. That's why u get error. Either make @IsBoolean() or remove @Transform()

**Comment by zachzhao1984** [comment] 2021-11-29 05:58
I just want undefined not to be tranformed to false actually

**Comment by orimdominic** [comment] 2022-03-10 03:22
> 

What's more odd? Even when the `IsOptional` decorator is used, it still throws a 400

**Comment by orimdominic** [comment] 2022-03-10 03:23
> > "false" is true ... In my opinion, this should not be casted, correct type or transform annotation should be used.
> > ```
> > @Transform(({ obj }) => {
> >     return [true, 'enabled', 'true'].indexOf(obj.isAnnotate) > -1;
> > })
> > ```
> 
> Good Job!
> 
> I was looking for it! Is there any way to return an error if no "true" or "false" was sent? I think to accept any value (that not be true) as false is weird.
> 
> Other way could be use with class-validator:
> 
> ```
>   @Transform(({ value }) => {
>     return [true, 'enabled', 'true'].indexOf(value) > -1;
>   })
>   @IsBooleanString()
>   isUnlocked: boolean;
> ```
> 
> but just does not work for me and I don't have any idea about what is happening When I use it with "IsBooleanString" decorator, I just receive, 400 bad request that says "isUnlocked must be a boolean string".
> 
> I would throw a 400 BAD REQUEST exception error if no "true" or "false" was sent.


What's more odd? Even when the `IsOptional` decorator is used, it still throws a 400

**Comment by andrebrito** [comment] 2022-05-12 23:56
Hey, guys.
I'm in a similar place. Using [@joanna-liana's answer](https://github.com/nestjs/nest/issues/3156#issuecomment-623871318), I've manage to work around like this:
```
// dto
@IsOptional()
@IsBoolean()
@Transform(({ value }) => {
  if (value === 'true') return true;
  if (value === 'false') return false;
  return value;
})
private: boolean;
```

```
// controller
@UsePipes(
  new ValidationPipe({
    always: true,
  }),
)
```

It's fishy, but it works.

**Comment by zaptree** [comment] 2023-08-24 13:26
I think a good argument for why 'false' should be treated as false is that class transformer gets used for parsing using requests and if the request is a GET and not a post all values get converted into strings thus false becomes 'false'. I'm having this trouble when using nestjs and doing GET requests. I use the `qs` lib to convert my request object `qs.stringify(requestObject)` which in the end my 'false' becomes true.

**Comment by dexat0r** [comment] 2024-04-18 15:48
For me worked ```IsBooleanString``` decorator:

DTO:
```
@IsBooleanString()
@IsOptional()
isEnabled?: boolean
```

Controller:
```
@Get("/")
public async getEnabled(@Query(new ValidationPipe({ transform: true })) query: DTO) { ... }
```

**Comment by NoNameProvided** [comment] 2024-05-04 11:02
Duplicate of https://github.com/typestack/class-transformer/issues/550.

**Closed by NoNameProvided** 2024-05-04 11:02 UTC
Labels: type: feature, status: duplicate
