### ISSUE TITLE
fix: Transform fails if the constructor expects an argument

### ISSUE THREAD

**Issue by pavankris** [typestack/class-transformer#1385] opened 2022-11-02 13:25 UTC
### Description

https://github.com/typestack/class-transformer/blob/develop/src/TransformOperationExecutor.ts#L160
TargetType is DecimalJS https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L4285 
and the valueType is Decimal 
None of the if block in TransformOperationExecutor.ts covers this as a result it falls into 
`newValue = new (targetType as any)();`
and the default constructor expects a valid argument 

but if we pass
`newValue = new (targetType as any)(value);`
everything works

### Expected behavior
Why shouldn't the value be passed in constructor ?

**Comment by bijela-gora** [comment] 2023-01-10 10:21
@pavankris hi!

> Why shouldn't the value be passed in constructor ?

I think because class-transformer doesn't support such case. The reasons might be the follow:
1. It is possible to define anything as a constructor parameter, for example an array: https://github.com/typestack/class-transformer/issues/1381#issue-1422898041
2. Or constructor might have multiple parameters.

Those two points should tell us, that to support such feature we need to change somehow interface of `plainToInstance` function, in order to give it a info of how to get constructor parameters and how they should look like.

**Comment by diffy0712** [comment] 2024-05-22 21:29
The issue does not contain a simple reproduction case.

Closing as invalid.

**Closed as not planned by diffy0712** 2024-05-22 21:29 UTC
Labels: type: fix, status: invalid
