### ISSUE TITLE
fix: bug in casting boolean properties from `@Query()` in Nest.js 

### ISSUE THREAD

**Issue by sebasmrl** [typestack/class-transformer#1696] opened 2024-04-30 05:42 UTC
### Description

Exist a bug with boolean transformers, when you try casting boolean property from @Query() in Nest.js @IsBoolean() it does not work correctly, i tried doing with @Transfromer() and its execution callback repeat 2 times if you use others decorators,  it's supposed to work using @IsBooolean() and @IsOptional() but is not.I was able to solve it doing a OR condition with @Tranformer()

**Minimal code-snippet showcasing the problem**
 

```ts
//Controller method
 @Get()
  findAll( @Query() paginationDto: PaginationDto) {
    return this.usersService.findAll(paginationDto);
  }

//Bug example code when you  trying to read 
export class PaginationDto{
    @IsOptional()
    @IsBoolean()
    activeRegisters?:boolean;
}

//Momentary solution
export class PaginationDto{
    @IsOptional()
    @IsBoolean()
    @Transform(({ value} ) => { 
        console.log("TRANSFORM: ",typeof value, value)
        return  (value == 'false' || value==false) ? false: true;
        } )
    activeRegisters?:boolean;
}
```

### Expected behavior

it's supposed to work using @IsBooolean() and @IsOptional() but is not.

### Actual behavior

In all other cases it works perfectly, only with @Query() results have problems

**Comment by diffy0712** [comment] 2024-05-01 11:01
Hello,

could you please describe your problem a bit more? I do not fully understand your problem. I do think you are mixing some things up here. The `@IsBooolean()` and `@IsOptional()` are decorators for [class-validator](https://github.com/typestack/class-transformer) and not this `class-transformer` library.

Neither `class-transformer` nor `class-validator` has  `@Query` decorator, so I assume by your example that that is some framework's decorator (nest?).

Does the `@Query` decorator call the `plainToInstance` or other `class-transformer` functions?

**Comment by diffy0712** [comment] 2024-05-03 21:35
Hi @sebasmrl,

This may be a duplicate of https://github.com/typestack/class-transformer/issues/626
Could you please check it if you experience the same problem.

I assume when using '@query' the plain contains booleans as strings, is that right for your situation?

**Comment by NoNameProvided** [comment] 2024-05-04 10:55
The issue does not contain a simple reproduction case. 

Closing as invalid.

**Closed as not planned by NoNameProvided** 2024-05-04 10:55 UTC
Labels: type: fix, status: invalid
