### ISSUE TITLE
Exposing a property using a different name

### ISSUE THREAD

**Issue by emcho92** [typestack/class-transformer#37] opened 2016-12-23 17:56 UTC
`@Expose({ name: "something" })`

This does not work. The property still has the same name and it's value is now undefined.

**Comment by nhitchins** [comment] 2017-10-16 03:07
+1

**Comment by NoNameProvided** [comment] 2018-10-26 18:29
Hi! 

I will go ahead and close this as solved because I cannot reproduce it with the provided description. Feel free to comment with a repro case if it's still not working for you.

**Closed by NoNameProvided** 2018-10-26 18:29 UTC
Labels: status: cannot reproduce, type: fix
