### ISSUE TITLE
fix: Expose not working correctly with toClassOnly

### ISSUE THREAD

**Issue by kpiatkowski** [typestack/class-transformer#1692] opened 2024-04-08 13:20 UTC
### Description
I have data that is incoming from 3rd party provider, and I need to transform properties to my internal structure and be able to export it that way too. Basically I just need to transform keys while importing.

```ts
class TestClass {
  @Expose({ name: "Test", toClassOnly: true })
  public test: string;
}

const instance = plainToInstance(TestClass, { Test: "something" });
const plain = instanceToPlain(instance);

console.log(instance);
console.log(plain);
```

### Expected behavior
```
TestClass { test: 'something' }
{ test: 'something' }
```

### Actual behavior
```
TestClass { test: 'something' }
{ Test: 'something' }
```

**Comment by diffy0712** [comment] 2024-05-05 11:53
Duplicate of https://github.com/typestack/class-transformer/issues/1324

**Closed as not planned by diffy0712** 2024-05-05 11:53 UTC
Labels: status: duplicate
