### ISSUE TITLE
feature: Support 'and' operator between groups

### ISSUE THREAD

**Issue by RadekKpc** [typestack/class-transformer#1560] opened 2023-07-03 11:38 UTC
### Description
When we use `groups` option decorators are applied when at least one group is passed to the `planToInstance`. Could you please make it possible to change that logic and apply decorators when all members of the group are presented? (Or provide some generic solution for that condition)

### Proposed solution
When we use:
```typescript
plainToInstance(Class, plainObject, { groups: ['a'] });
```
Now:
```typescript
@Expose({groups: ['a','b','c']})
```
will be applied when 'a' **or** 'b' **or** 'c' is given

Expected:
```typescript
@Expose({groups: ['a','b','c'], strictGroupsBehaviour: true })
```
will applied when 'a' **and** 'b' **and** 'c' is given

**Comment by RadekKpc** [comment] 2023-07-03 11:43
Probably duplicated https://github.com/typestack/class-transformer/issues/203

**Comment by diffy0712** [comment] 2024-05-08 16:40
Duplicate of https://github.com/typestack/class-transformer/issues/203

**Closed as not planned by diffy0712** 2024-05-08 16:40 UTC
Labels: type: feature, status: duplicate, flag: needs discussion
