### ISSUE TITLE
nested objects with class-transformer's plainToClass fails

### ISSUE THREAD

**Issue by gordielachance** [typestack/class-transformer#1494] opened 2023-04-01 18:50 UTC
### Description

Based on [the example here](https://github.com/typestack/class-transformer#working-with-nested-objects), I have this code

    import { Type, plainToClass } from 'class-transformer';
    import 'reflect-metadata';

    export class Album {
      id: number;

      name: string;

      @Type(() => Photo)
      photos: Photo[];
    }

    export class Photo {
      id: number;
      filename: string;
    }

    const albumJson = {
      id:12,
      name:"album",
      photos:[
        {
          id:01,
          filename:"photo1.jpg"
        }
      ]
    }

    let album = plainToClass(Album, albumJson);

But it does not work : I get this error:

> Unable to resolve signature of property decorator when called as an
> expression.   Argument of type 'undefined' is not assignable to
> parameter of type 'Object'. @Type(() => Photo)

Thanks !

### Expected behavior
Have it to work :)

### Actual behavior
I get this error
> Unable to resolve signature of property decorator when called as an
> expression.   Argument of type 'undefined' is not assignable to
> parameter of type 'Object'. @Type(() => Photo)

**Comment by bhaugeea** [comment] 2023-04-03 20:23
It works for me in this codesandbox: https://codesandbox.io/s/elegant-ellis-pzhisz?file=/src/index.ts

Can you link a repro?

**Comment by guradia** [comment] 2023-06-23 13:39
I can confirm this problem, as being purely during linting (in VSCode in my case)
On compile, it does not show up (probably some ignore setting or no strict linting)

But comparing your sandbox's tsconfig.json i found the simple difference:
`"experimentalDecorators": true,`

This made my VSCode linting implementation accept the typeFunction.

**Comment by diffy0712** [comment] 2024-05-14 21:52
Closing as answered. If you have any questions left feel free to comment on this issue.

**Closed as completed by diffy0712** 2024-05-14 21:52 UTC
Labels: type: fix, status: invalid, status: needs triage
