### ISSUE TITLE
fix: When I use `plainToClass` in my nestjs app to validate nested env it cannot convert them

### ISSUE THREAD

**Issue by kasir-barati** [typestack/class-transformer#1519] opened 2023-04-28 15:26 UTC
### Description
I am using class-validator and class-transformer to validate my `.env` but it cannot validate nested objects even though I am using `@type(() => ClassName)` in my code. But at the same time I am able to validate incoming http request with it. I mean I created a dummy endpoint which receives an object with a nested object inside it and it works just fine. IDK what i am doing wrong. I really appreciate your helps.

**Minimal code-snippet showcasing the problem**
https://github.com/kasir-barati/bugs/tree/class-transformer-bug
Clone the repo and follow the instructions in the `readme.md`

### Expected behavior
Validate the `.env` successfully and not log the value of `KEYCLOAK_SECRET` like a string.

### Actual behavior
It cannot convert the type `KEYCLOAK_SECRET` to it's respective type as I code.

**Comment by addun** [comment] 2023-05-19 07:54
There is no bug in class-transformer/class-validation. The problem is with your configuration.

1. Your env (KEYCLOAK_SECRET) is a JSON, so you need to parse is into object. You can do this by adding `Transform`
```ts
class EnvironmentVariables {
  @ValidateNested()
  @Transform(({ value }) => JSON.parse(value)) // <- this line of code
  @Type(() => KeycloakSecretValidator)
  KEYCLOAK_SECRET: KeycloakSecret;
}
```

2. `process.env` contains not only properties from `.env` but much more so you have two solutions:

* Set `forbidUnknownValues` as `false`
```ts
  const validatedConfigsErrors = validateSync(validatedConfigs, {
    skipMissingProperties: false,
    forbidUnknownValues: false, // <- this line
    forbidNonWhitelisted: true,
  });
```

* Or add `expose` and remove all unknown properties during parsing to class:
```ts
class EnvironmentVariables {
  @ValidateNested()
  @Transform(({ value }) => JSON.parse(value))
  @Type(() => KeycloakSecretValidator)
  @Expose() // < -- this line of code
  KEYCLOAK_SECRET: KeycloakSecret;
}
```
```ts
  const validatedConfigs = plainToClass(EnvironmentVariables, config, {
    enableImplicitConversion: true,
    excludeExtraneousValues: true, // <- this line of code
  });
```

After this changes it should work

**Comment by kasir-barati** [comment] 2023-05-19 11:40
Thanks for the clarification, but still I cannot stop wondering why in the [`auth.config.ts`](https://github.com/kasir-barati/bugs/blob/class-transformer-bug/src/auth/auth.config.ts) I have to go through that `@Transform(({ value }) => JSON.parse(value))` and in [`t.dto`](https://github.com/kasir-barati/bugs/blob/class-transformer-bug/src/auth/t.dto.ts) I do not need to do that?

![image](https://github.com/typestack/class-transformer/assets/73785723/ddc4e8ff-226c-47e6-b14e-d356fdc47c99)

Though I think basically my [global `ValidationPipe` in `main.ts`](https://github.com/kasir-barati/bugs/blob/class-transformer-bug/src/main.ts) is the same as what I did at [`auth.config.ts`](https://github.com/kasir-barati/bugs/blob/class-transformer-bug/src/auth/auth.config.ts#L37-L39), are not they?

**Comment by addun** [comment] 2023-05-19 11:55
Because nestjs have built in parser from JSON to plain JS object when request comes from API (via controller). So nestjs does it but under the hood.

When you load data to app via env, nestjs parser is not run, so you have to do it manually.

---

```ts
  app.useGlobalPipes(
    new ValidationPipe({
      transformOptions: {
        enableImplicitConversion: false,
      },
    }),
  );
```

This global pipe only touch HTTP requests, not all used of class-transform/class-validation

**Comment by kasir-barati** [comment] 2023-05-19 16:55
> This global pipe only touch HTTP requests, not all used of class-transform/class-validation

I knew this, but I did not know about the builtin parser. Thanks a lot. Now everything is clear as day to me.

**Comment by emileindik** [comment] 2023-10-17 21:13
Question--
Is it not possible to get the exact list of properties from the class itself, and to tell `plainToClass()` to only parse those properties? Why is it necessary to add `Expose()` to each property? On the surface, seems redundant.

**Comment by addun** [comment] 2023-11-22 20:49
Nope, it is not possible. Properties declarations only exist in TS. Library has to somehow get those information and is does... but from `Expose` decorator.

You can read more about it in [README.md](https://github.com/typestack/class-transformer#enforcing-type-safe-instance)

**Comment by diffy0712** [comment] 2024-05-09 20:49
Closing as answered. If you have any questions left feel free to comment on this issue.
Thank you @addun for the answer!

**Closed as completed by diffy0712** 2024-05-09 20:49 UTC
Labels: type: fix, status: needs triage
