### ISSUE TITLE
Date not converting to string in classToPlain

### ISSUE THREAD

**Issue by oeed** [typestack/class-transformer#213] opened 2018-11-29 02:00 UTC
Hi there,

We're finding that Dates aren't being converted to strings like it says should happen in the docs, instead it leave it as a Date object.

I managed to get it working by manually converting it as so:
```
@Transform((date: Date | null) => date ? date.toISOString() : null, { toPlainOnly: true })
departure_time: Date // results in a string, as desired
```

Buy just using `@Type` doesn't work like is suggested in the docs:
> Note, that dates will be converted to strings when you'll try to convert class object to plain object.

```
@Type(() => Date)
return_time: Date // results in the { buffer: ... } object
```

Are we doing something wrong or is it necessary do to this?

**Comment by MTschannett** [comment] 2018-11-29 10:17
This seems like a regression. It's stated like this in the documentation.

**Comment by oleic** [comment] 2019-06-02 21:12
This issue still exists. @oeed solutions seem not work for me with version v0.2.3.

v0.1.10 is the last version where the transformation works as documented.

**Comment by belvederef** [comment] 2019-08-22 09:06
I am on `v0.2.3` and it works fine for me.

**Comment by NoNameProvided** [comment] 2020-08-02 22:33
Closing as cannot reproduce. If you are still experiencing the issue please provide a minimal reproduction case.

**Closed by NoNameProvided** 2020-08-02 22:33 UTC
Labels: status: cannot reproduce, type: fix
