### ISSUE TITLE
Transform fails for properties of type: custom type array or null

### ISSUE THREAD

**Issue by tompetko** [typestack/class-transformer#107] opened 2017-11-02 10:58 UTC
Deserialization of object with property defined like this:
```
@Type(() => User)
Users?: User[] | null;
```
fails with error:
```
TypeError: newValue_1.push is not a function

  at src/TransformOperationExecutor.ts:47:34
  at Array.forEach (native)
  at TransformOperationExecutor.Object.<anonymous>.TransformOperationExecutor.transform (src/TransformOperationExecutor.ts:40:30)
  at _loop_1 (src/TransformOperationExecutor.ts:167:43)
  at TransformOperationExecutor.Object.<anonymous>.TransformOperationExecutor.transform (node_modules/class-transformer/TransformOperationExecutor.js:178:17)
  at ClassTransformer.Object.<anonymous>.ClassTransformer.plainToClass (src/ClassTransformer.ts:43:25)
  at plainToClass (src/index.ts:37:29)
```
Deserialization of basic type array properties like this:
```
Codes?: string[] | null;
```
works as expected.

`class-transformer` version is `0.1.8`

**Comment by godenji** [comment] 2018-03-03 05:48
Any idea what's going on here, getting the same trying to `@Type` any `T[]`s (where `T` is a concrete type)

v0.1.9

**Comment by mohyt** [comment] 2018-07-23 15:42
I faced same issue today, it seems to me it is related to Reflect.getMetadata("design:type", ...)
@tompetko : Do you have any workaround for this?

**Comment by NoNameProvided** [comment] 2018-10-26 17:31
Hi @tompetko 

I cannot reproduce this anymore. This is the test code I have tried with: 

```ts
import 'reflect-metadata';
import { Type, plainToClass } from 'class-transformer';

class User {
  firstName: string;
  lastName: string;

  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}

class Example {
  @Type(() => User)
  users: User[] | null;
}


const payload = { users: [ { firstName: 'User', lastName: '#1'}, { firstName: 'User', lastName: '#2'} ] };
const transformed = plainToClass(Example, payload);

transformed.users.forEach(u => console.log(u.fullName));
```

The full name of the usrs get printed as expected.

I will go ahead and close this, feel free to continute the discussion here if you have any more questions.

**Closed by NoNameProvided** 2018-10-26 17:31 UTC
Labels: comp: transformations, status: cannot reproduce, type: fix

**Comment by balkarov** [comment] 2019-03-22 14:57
I have the same problem

**Comment by NoNameProvided** [comment] 2019-05-11 17:14
> I have the same problem

@balkarov  If you are still experiencing the issue, please open a new ticket with a reproducible example.
