### ISSUE TITLE
feat: support automatic casting of the string representation of a boolean value

### ISSUE THREAD

**Issue by mubin-ct** [typestack/class-transformer#1328] opened 2022-09-04 03:23 UTC
### Description
If we try to convert a value that has `typeof string`, then in some cases it returns the wrong value. e.g `value: 'true'` will return true, while on the other hand `value: 'false'` will also return the true.

**Minimal code-snippet showcasing the problem**
Consideration: A network access request.

```ts
import { Expose, plainToInstance } from 'class-transformer';

class RoleDTO {
  @Expose()
    id: number
  @Expose()
  canAccess: boolean
}
plainToInstance(RoleDTO, { id: 1, canAccess: 'true' }, { enableImplicitConversion: true })
plainToInstance(RoleDTO, { id: 2, canAccess: 'false' }, { enableImplicitConversion: true })
```

### Expected behavior
`RoleDTO` with the `id:1` should have `canAccess: true` and  `RoleDTO` with the `id:2` should have `canAccess: false` 
### Actual behavior
`RoleDTO` with `id` 1, and 2 have `canAccess: true`

This is a common JS Boolean conversion issue, I will be submitting a PR for this.

**Comment by andylizf** [comment] 2024-03-22 16:19
any update?

**Comment by NoNameProvided** [comment] 2024-05-04 11:00
Duplicate of https://github.com/typestack/class-transformer/issues/550.

**Closed as not planned by NoNameProvided** 2024-05-04 11:00 UTC
Labels: type: feature, status: duplicate
