### ISSUE TITLE
why I get an empty ObjectId?

### ISSUE THREAD

**Issue by cityvoice** [typestack/class-transformer#1484] opened 2023-03-22 11:56 UTC
### Description

I have a nestjs project, my collection was imorted from an json file. When I query the collection, _id field is an empty object.

**Minimal code-snippet showcasing the problem**
 

```ts

```

### Expected behavior

fee.schema.ts
```
import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";
import { Exclude, Expose, Transform } from "class-transformer";
import mongoose, { HydratedDocument, Types } from "mongoose";
import { ObjectId } from "mongodb";
...
@Schema({
  collection: 'meta_fee',
  versionKey: false,
  toJSON: {
    getters: true,
    virtuals: true,
  },
})
@Exclude()
export class Fee {
  @ApiProperty({ description: 'ID' })
  @Prop({ type: Types.ObjectId})
  @Expose({ toPlainOnly: true })
  _id: Types.ObjectId;

  @ApiPropertyOptional({ description: 'name' })
  @Prop()
  @Expose()
  name: string;
}
...
```

fee.service.ts
```
...
async findAll(){
return await this.feeModel.find().lean()
}
```

### Actual behavior

the query returns:
```
[
{
"_id":{}, //just get an empty object
"name":  "name 1"
},
{
"_id":{},
"name":  "name 2"
}
]
```

I have tried everything such as modify schema to 

```
  @ApiProperty({ description: 'ID' })
  @Prop()
  @Expose()
  _id: Types.ObjectId;

```
or 

```
  @ApiProperty({ description: 'ID' })
  @Prop({ type: Types.ObjectId})
  @Expose({ toPlainOnly: true })
  @Transform(() => Types.ObjectId)
  _id: Types.ObjectId;
```

all doesn't work. why?

**Comment by cityvoice** [comment] 2023-03-22 13:09
should i have touse $toString in project to convert ObjectId to String? But I think it's a stupid idea.

**Comment by cityvoice** [comment] 2023-03-22 14:30
If I change the fee.service.ts to 
import { plainToInstance } from 'class-transformer';
async findAll(){
const list = await this.feeModel.find().lean()
return plainToInstance(Fee, list); //Fee is my schema
}

then i change the Decorate to 

  @ApiPropertyOptional({ description: 'ID' })
  @Prop({ type: Types.ObjectId })
  @Transform(({ value }) => value.valueOf())
  @Expose()
  _id: Types.ObjectId;

it works. so who can tell me what happened, i just want return _id as an ObjectID or Object String instead of an empty object. AND don't want to write so many code.

**Comment by yonglezhou** [comment] 2023-04-03 04:45
When the class entity transform back to plain by classToPlain(), the ObjectId value transform to default value "{}", because Object.keys(objectIdValue) return "[]", it cannot transform any properties.

**Comment by diffy0712** [comment] 2024-05-09 21:10
The issue does not contain a simple reproduction case.

Closing as invalid.

**Closed as not planned by diffy0712** 2024-05-09 21:10 UTC
Labels: type: fix, status: invalid
