### ISSUE TITLE
Nested map?

### ISSUE THREAD

**Issue by jcstudio-jeff-chen** [typestack/class-transformer#1364] opened 2022-10-12 07:13 UTC
```
class ClassA {
  x: number;
  y: number;
}
class ClassB {
  @Type(() => ClassA)
  a: Map<string, Map<string, ClassA>>;
}

const plainObj = {a: {b: {c: {x: 1, y:2}}}};
const b = plainToInstance(ClassB, plainObj);
```
The code above doesn't work because nested Map is not supported.
Is it possible in the near future?

**Comment by ghost** [comment] 2023-08-04 09:22
Has this been implemented or fixed?

**Comment by victor-shelepen** [comment] 2023-08-18 14:19
Hello. I also need the functionality. It does not convert map values.
I apply extra conversion for map values. So it works without the decorator ```@Type``` and ```@ValidateNested``` starts working.
```typescript
...
@Transform(
  ({ value }) =>
    new Map(
      Object.entries(value).map(([key, value]) => [
        key,
        plainToInstance(ImportDefinitionMappingDTO, value),
      ])
    ),
  { toClassOnly: true }
)
@ValidateNested({ each: true })
...
```

**Comment by diffy0712** [comment] 2024-05-22 21:39
Duplicate of https://github.com/typestack/class-transformer/issues/1256

**Closed as not planned by diffy0712** 2024-05-22 21:39 UTC
Labels: status: duplicate
