### ISSUE TITLE
question: transformations on arrays

### ISSUE THREAD

**Issue by chriswhite199** [typestack/class-transformer#72] opened 2017-07-11 22:00 UTC
Is it possible to perform transformations on an array field?

For example say on the wire / json i have an array of CSV strings, which i want to deserialize into an array of pairs.

Here's a sample test (added into transformer-method.spec.ts) to demonstrate further:

```
it("should allow array transformations", () => {
        class TopLevel {
            @Type(() => Child)
            @Transform((values: string[]) => values.map(value => Child.fromCsv(value)), {toClassOnly: true})
            @Transform((values: Child[]) => {
                console.log("Values:     " + JSON.stringify(values));
                console.log("1st value:  " + JSON.stringify(values[0]));
                console.log("is a Child: " + (values[0] instanceof Child));
                console.log("type:       " + (typeof values[0]));
                return values.map(value => value.toCsv());
            }, {toPlainOnly: true})
            children: ChildCollection;
        }

        class ChildCollection extends Array<Child> {

        }

        class Child {
            prop1: string;
            prop2: string;

            toCsv() {
                return [this.prop1, this.prop2].join(",");
            }

            static fromCsv(csv: string) {
                const child = new Child();
                [child.prop1, child.prop2] = csv.split(",");
                return child;
            }
        }

        const top = new TopLevel();
        top.children = [];
        top.children.push(Child.fromCsv("123,abc"));

        console.log("children:   " + JSON.stringify(top.children));
        console.log("1st child:  " + JSON.stringify(top.children[0]));
        console.log("is a Child: " + (top.children[0] instanceof Child));
        console.log("type: " + (typeof top.children[0]));

        // deserialization works without an issue
        const expectedSerialized = {children: ["123,abc"]}
        const deserialized = plainToClass(TopLevel, expectedSerialized);
        expect(deserialized).to.deep.equal(top);

        // serialization has an issue however
        const actualSerialized = classToPlain(top);
        expect(actualSerialized).to.deep.equal(expectedSerialized);
    });
```

The test fails with the following error:

```
  transformer methods decorator

children:   [{"prop1":"123","prop2":"abc"}]
1st child:  {"prop1":"123","prop2":"abc"}
is a Child: true
type: object

Values:     [{"prop1":"123","prop2":"abc"}]
1st value:  {"prop1":"123","prop2":"abc"}
is a Child: false
type:       object

    1) should allow array transformations
    ✓ should expose non configuration properties and return User instance class
    ✓ should expose non configuration properties
    ✓ should expose non configuration properties and properties with specific groups
    ✓ should expose non configuration properties with specific version


  53 passing (280ms)
  1 failing

  1) transformer methods decorator should allow array transformations:
     TypeError: value.toCsv is not a function
      at build/es5/test/functional/transformer-method.spec.js:39:71
      at Array.map (native)
      at TransformMetadata.decorators_1.Transform.toPlainOnly [as transformFn] (build/es5/test/functional/transformer-method.spec.js:39:35)
      at build/es5/src/TransformOperationExecutor.js:9:16977
      at Array.forEach (native)
      at TransformOperationExecutor.applyCustomTransformations (build/es5/src/TransformOperationExecutor.js:9:16856)
      at _loop_1 (build/es5/src/TransformOperationExecutor.js:9:13244)
      at TransformOperationExecutor.transform (build/es5/src/TransformOperationExecutor.js:9:14567)
      at ClassTransformer.classToPlain (build/es5/src/ClassTransformer.js:9:802)
      at Object.classToPlain (build/es5/src/index.js:9:1017)
```

The console.log debug statements show that when the children object is passed to the `@Transform` decorator function, it's no longer an array of Child objects (but an array of POJOs), and hence calling the Child::toCSV() method on it fails.

Is this a bug, or is there another pattern i should be using to use transformers on arrays? (Deserialization works as expected)

**Comment by gempain** [comment] 2017-07-12 07:51
As far as I can see, there is no such method as `toCsv` on the native Javascript [String prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/prototype). If you are using a package that adds that method to the String prototype, make sure to import it at the beginning of your test. 

Before doing any further investigation, I would suggest that you fix that part of your test and then update the console error.

**Comment by chriswhite199** [comment] 2017-07-12 15:54
But when converting from classToPlain, i'm passing a typed object (TopLevel), which has typed child objects (Child) - my issue is that during the transformation, the objects lose their typing when they reach the transformation function:

```
            // I would assume as the input object is a typed class, the values object here should be typed to, but isn't as you can see from the console output
            @Transform((values: Child[]) => {
                console.log("Values:     " + JSON.stringify(values));
                console.log("1st value:  " + JSON.stringify(values[0]));
                console.log("is a Child: " + (values[0] instanceof Child));
                return values.map(value => value.toCsv());
            },
            // toPlainOnly - i would assume means only apply this tx when converting from a class to a plain js object
            {toPlainOnly: true})
            children: ChildCollection;
```

as proved by the console output, even though going into the transformation the objects are typed, they are NOT typed when they reach my tx function:

```
// types before they are passed to classToPlain:
children:   [{"prop1":"123","prop2":"abc"}]
1st child:  {"prop1":"123","prop2":"abc"}
is a Child: true
type: object

// types inside my tx function:
Values:     [{"prop1":"123","prop2":"abc"}]
1st value:  {"prop1":"123","prop2":"abc"}
is a Child: false
type:       object
```

This isn't an issue of the toCSV() method not being present on a String object, as the input objects here are not strings, but objects (as you can see in the console output: `type: object` - which have lost their typing and are now just plain objects, and hence my toCSV() method doesn't exist).

Is there some blackbox magic that occurs on the typed object when passed to classToPlain that would explain this?

**Comment by chriswhite199** [comment] 2017-09-26 04:57
OK here's a Plunker showing the issue: http://plnkr.co/edit/MOcL32

Open the plunker, open the console and you'll see it fails - now go inspect the model/persons.ts file and switch the @Transform decorator, now you'll see no failure.

The object appears to lose its typing when an array is passed to @Transform for `toPlainOnly: true`

@gempain - over to you

**Comment by gempain** [comment] 2017-10-03 09:46
@chriswhite199 checking :)

**Comment by gempain** [comment] 2017-10-04 08:52
Alright, so it seems that this is an intended behavior, not a bug. Transform callbacks are called with a pre-transformed value, hence why the type is lost when your callback receives it.

I implemented a fix for your issue, and made a PR, but this is somehow a breaking change.

@pleerock what do you think ? (see PR comments)

**Comment by justvovus** [comment] 2017-12-22 08:02
Hi @gempain,
I also had related problem: in my transformation to plain I am calling a method on my value, but pre-transformed value has no that method anymore.
I tried your fix and it solves the problem just fine for me.
Could you please tell me when do you plan to merge it and add to the version release?
Thanks.

**Comment by gempain** [comment] 2018-02-18 12:03
@justvovus No idea, I'm not a maintainer, just a contributor. Don't worry, it'll go through at some point :)

**Comment by NoNameProvided** [comment] 2018-10-26 18:41
I see some merged commit for this. Is it fixed?

**Comment by JimLynchCodes** [comment] 2020-12-31 00:06
So what's the answer to OP's original question?

**Comment by NoNameProvided** [comment] 2021-02-14 19:02
I cannot reproduce. The `@Transform` decorator receives the original value from the class instance as expected. In your Transform call, you can do whatever you want with it.  

```ts
import 'reflect-metadata';
import { classToPlain, Type, Transform } from './index';

class SubClass {
  public id!: number;
}

class ExampleClass {
  @Type(() => SubClass)
  @Transform((({ value }) => {
    console.log(value[0] instanceof SubClass);
    console.log(value[1] instanceof SubClass);
    // prints true twice as expected
    return value;
  }))
  public children!: SubClass[];
}

const instance = new ExampleClass();

instance.children = [ new SubClass(), new SubClass() ]
instance.children[0].id = 0;
instance.children[1].id = 1;

console.log(classToPlain(instance));
// prints { children: [ { id: 0 }, { id: 1 } ] }
```

**Closed by NoNameProvided** 2021-02-14 19:02 UTC
Labels: status: cannot reproduce, type: question
