### ISSUE TITLE
fix: wrong docstring that instanceToClass should be changed to plainToInstance

### ISSUE THREAD

**Issue by tmac12** [typestack/class-transformer#1413] opened 2022-12-13 15:03 UTC
### Description
The instanceToClass function doesn't exist. It should be changed to the plainToInstance function.

**Minimal code-snippet showcasing the problem**
Wrong deprecated suggestion, `instanceToClass` doesn't exists.

```ts
/**
 * Deserializes given JSON string to a object of the given class.
 *
 * @deprecated This function is being removed. Please use the following instead:
 * ```
 * instanceToClass(cls, JSON.parse(json), options)
 * ```
 */
export declare function deserialize<T>(cls: ClassConstructor<T>, json: string, options?: ClassTransformOptions): T;
/**
 * Deserializes given JSON string to an array of objects of the given class.
 *
 * @deprecated This function is being removed. Please use the following instead:
 * ```
 * JSON.parse(json).map(value => instanceToClass(cls, value, options))
 * ```
 *
 */
export declare function deserializeArray<T>(cls: ClassConstructor<T>, json: string, options?: ClassTransformOptions): T[];
```

### Expected behavior
It suggest to use `instanceToClass` instead of `plainToInstance`.
```ts
/**
 * Deserializes given JSON string to a object of the given class.
 *
 * @deprecated This function is being removed. Please use the following instead:
 * ```
 * plainToInstance(cls, JSON.parse(json), options)
 * ```
 */
export declare function deserialize<T>(cls: ClassConstructor<T>, json: string, options?: ClassTransformOptions): T;
/**
 * Deserializes given JSON string to an array of objects of the given class.
 *
 * @deprecated This function is being removed. Please use the following instead:
 * ```
 * JSON.parse(json).map(value => plainToInstance(cls, value, options))
 * ```
 *
 */
export declare function deserializeArray<T>(cls: ClassConstructor<T>, json: string, options?: ClassTransformOptions): T[];
```

### Actual behavior
It suggest to use `instanceToClass` that doesn't exists.

**Comment by diffy0712** [comment] 2024-05-09 21:14
Duplicate of https://github.com/typestack/class-transformer/issues/1019

**Closed as not planned by diffy0712** 2024-05-09 21:14 UTC
Labels: status: duplicate
