### ISSUE TITLE
fix: Breaking changes in 0.3.2

### ISSUE THREAD

**Issue by AckerApple** [typestack/class-transformer#551] opened 2021-01-14 19:30 UTC
[This merged code gave me breaking changes](https://github.com/typestack/class-transformer/pull/538)

```
// before is now broken
@Transform(parseInt)

// after now fixed
@Transform((ob: TransformFnParams) => parseInt(ob.value))
```

IF this is now the way the code will work, you need to change the package.json version MINOR version at least please to signify a breaking change release

**Comment by NoNameProvided** [comment] 2021-01-14 19:31
Yes, that is slipped through. It is mentioned now in the changelog. 

Also, we are under the 1.0 release, so we don't have to respect semver yet. (We aim to respect it anyway.)

**Comment by NoNameProvided** [comment] 2021-01-14 19:31
Also please use the search before opening issues. This is a duplicate of #547.

**Closed by NoNameProvided** 2021-01-14 19:31 UTC
Labels: status: wontfix, type: fix

**Comment by AckerApple** [comment] 2021-01-14 20:05
I did search just not for "0.3.2" and you are closing the issues faster than other eyes can see them as recently reported issues.

**Comment by AckerApple** [comment] 2021-01-14 20:08
This need to be version 0.4.0 PLEASE as it has been months since last change and you released a breaking PATCH change

Hey you are breaking rules here... "we are under the 1.0 release" is a bad statement...

```
0.3.2 --- 13 hours ago
0.3.1 --- 6 months ago
0.2.3 --- 2 years ago
```


![image](https://user-images.githubusercontent.com/7964429/104643257-23b51180-567a-11eb-8343-dfbad58f8e95.png)
