### ISSUE TITLE
version and name options not working together

### ISSUE THREAD

**Issue by amir-khoshbakht** [typestack/class-transformer#1522] opened 2023-05-02 16:41 UTC
### Description
cant use "name" and "until"/"since" concurrently with @Expose() decorator.
the property name changes as expected but the until/since not working

```ts
import {
  plainToClass,
  Expose,
  classToPlain
} from "class-transformer";

class MyDTO {
  @Expose({ name: "first", since: 0, until: 1 })
  second: string;
}

const dto = plainToClass(MyDTO, { first: "testttttt" }, { version: 2, });
const obj = classToPlain(dto);
console.log(obj)
```

### Expected behavior
output :
```ts
"obj:" {} // the property version is until 1, so it shouldn't show up
```

### Actual behavior
output: 
```ts
"obj:" {
  "first": "testttttt"
}
```

**Comment by my-random-username** [comment] 2023-05-02 16:46
it seems its expected behavior. as documentation says :
The above decorators accept one optional argument: ClassTransformOptions - The transform options like groups, version, name

**Comment by diffy0712** [comment] 2024-05-09 20:45
Hello @amir-khoshbakht,

I think the problem is that you do not provide a version in your `instanceToPlain` call.

Should be `const obj = classToPlain(dto, {version: 2});`

**Comment by diffy0712** [comment] 2024-05-14 21:39
Closing as invalid. I do not think this is an error with the library (see comment above).
If you can add a detailed way to reproduce the error, feel free to comment on this issue.

**Closed as not planned by diffy0712** 2024-05-14 21:39 UTC
Labels: type: fix, status: invalid
