### ISSUE TITLE
Decorators not honoured when using classToPlain(object)

### ISSUE THREAD

**Issue by emlynmac** [typestack/class-transformer#105] opened 2017-11-02 02:53 UTC
I have an object, with an x: number and y: number properties.

`
@Expose({ name: 'coordsX' })
`
`
 x: number = 0;
`

`
 @Expose({ name: 'coordsY' })
`
`
 y: number = 0;
`

Using plainToClass(Object, values), I get the properties populated correctly.

Using classToPlain(object) I get the values { x, y } exposed - no translation is done.

@Exclude also does not work - I have worked around this by prefixing all methods / properties with _ and then:
`
classToPlain(object, { excludePrefixes: ['_'], });
`
It would be nice to have the decorators working properly

**Comment by chris-jones-pixitmedia** [comment] 2017-11-08 14:44
+1. excludePrefixes is not working for me either

**Comment by emlynmac** [comment] 2017-11-08 16:54
@chris-jones-pixitmedia I extended the API to allow you to pass in the type of class you want to serialize to and created a PR: #106 

If you want to build the stuff up and use it, I've got it forked here: https://github.com/emlynmac/class-transformer

It's allowed me to move forward without digging into the code of class-transformer too much.

**Comment by lincanli** [comment] 2018-05-02 10:39
I experienced same problem. Will it be fixed in next version?

**Comment by cojack** [comment] 2018-10-21 15:54
@emlynmac but hmm, does it still affects you?

**Comment by emlynmac** [comment] 2018-10-22 04:19
Has anything changed? Yes I still am using my fork in my current projects

**Comment by NoNameProvided** [comment] 2018-10-24 13:32
Hi @emlynmac and @lincanli! 

I cannot reproduce your issue with `0.1.10`. Here is how I tried: 

```ts
import { Expose, plainToClass, classToPlain } from 'class-transformer';

class Example {
  @Expose({ name: 'coordsX' })
  x: number;

  @Expose({ name: 'coordsY' })
  y: number;
}
const plainToClassResult = plainToClass(Example, { coordsX: 5, coordsY: 3 });
const classToPlainResult = classToPlain(plainToClassResult);

console.log(plainToClassResult); // logs expected "Example {x: 5, y: 3}" class
console.log(classToPlainResult); // logs expected "{coordsX: 5, coordsY: 3}" object
```

I will go ahead and close this, please feel free to continue the discussion if you have any more question.

**Closed by NoNameProvided** 2018-10-24 13:32 UTC
Labels: status: help wanted, type: question
