### ISSUE TITLE
fix: @Transform method error: Property 'xxx' does not exist on type 'TransformFnParams'

### ISSUE THREAD

**Issue by mirari** [typestack/class-transformer#539] opened 2021-01-14 07:28 UTC
### Description
0.3.1 works well.
0.3.2 report an error like this:
```
Property 'getTime' does not exist on type 'TransformFnParams'
```
```
value.getTime is not a function
```

**Minimal code-snippet showcasing the problem**
```ts
export class LogVO {
  @Expose()
  @Transform(value => value.getTime())
  createdAt: number;
}
```

I have to change it to:

```ts
export class LogVO {
  @Expose()
  @Transform(({ value }) => value.getTime())
  createdAt: number;
}
```

### Expected behavior
Just like the doc example.

### Actual behavior
Got an error:
```
Property 'getTime' does not exist on type 'TransformFnParams'
```

**Comment by iturn** [comment] 2021-01-14 12:09
I second this

**Comment by NoNameProvided** [comment] 2021-01-14 12:29
This is expected, watching from the changes, this was introduced when exposing the transformed property key to the decorator to prevent any further breaking changes when the signature changes. 

Sorry for this slipping through without a warning in the changelog, I will update it.

**Comment by rickkln** [comment] 2021-01-14 12:44
Not sure if related to this issue but also seem to be seeing problems with 0.3.2:
- Our build broke (no changes in our codebase) only change seems to be the class-transformer dependency being used in `@nestjsx/crud-typeorm` and going from 0.3.1 to 0.3.2. 
- Error is `Cannot find module 'class-transformer' or its corresponding type declarations` within the @nestjsx/crud-typeorm package (so something in the ts setup seems wrong). 
I would assume its any issue on our side but:
- fixing the version of this package to 0.3.1 seems to fix it.
- also started right when 0.3.2 was released.

**Comment by NoNameProvided** [comment] 2021-01-14 15:19
Fixed in c88860f374e6b2a81715026da6618794946cc210 and 1f33bf2f5ec4429dec80481794fd8624b20529c2.

**Closed** 2021-01-14 15:19 UTC
Labels: status: done/released, type: documentation

**Comment by NoNameProvided** [comment] 2021-01-14 15:20
@rickkln Please do not comment tour issues on unrelated bug reports, if your issue still persists please open a new issue with a minimal reproducible example. Thanks!

**Comment by rickkln** [comment] 2021-01-14 16:18
I only commented here because I thought my issue probably related to this one 😄 I have now created the separate issue here:  https://github.com/typestack/class-transformer/issues/547

**Comment by rickkln** [comment] 2021-01-14 16:25
Turns out it was related 😅 1f33bf2f5ec4429dec80481794fd8624b20529c2 seems to have fixed the issue on the `@nestjsx/crud-typeorm` side. Thanks for the quick fix!
