### ISSUE TITLE
fix: if constructor is a property, plainToClass will throw a error

### ISSUE THREAD

**Issue by ALCLCGS** [typestack/class-transformer#1462] opened 2023-02-28 07:36 UTC
### Description
```ts
const plain = {constructor:{xxx:"xxxx"}};
const result = plainToClass(User, plain);
```

it will throw a error when targetType is undefined and constructor is a Object property
error : Cannot read property 'constructor' of undefined

<img width="814" alt="image" src="https://user-images.githubusercontent.com/41117090/221783495-f55524c9-75ef-4d98-80f6-37542bf4722f.png">

### Expected behavior
It is better to assign "constructor" to a constructor function

### Actual behavior
"constructor" assigns a value to an object

**Comment by diffy0712** [comment] 2024-05-14 22:02
Hello @ALCLCGS,

I was unable to reproduce this.
Could you please give an example on how your `User` class looks like?

**Comment by diffy0712** [comment] 2024-05-21 19:57
The issue does not contain a simple reproduction case.

Closing as invalid.

**Closed as not planned by diffy0712** 2024-05-21 19:57 UTC
Labels: type: fix, status: invalid, status: needs triage
