### ISSUE TITLE
"TypeError: Class constructor User cannot be invoked without 'new'" When used with Sequelize models

### ISSUE THREAD

**Issue by SamiSammour** [typestack/class-transformer#242] opened 2019-03-17 20:01 UTC
I'm having this error when using with `sequelize` models when trying to `classToPlain` on a `sequelize` mode class.
The problem can be recreated with the following code:
```typescript
import 'reflect-metadata';
import { plainToClass, classToPlain } from 'class-transformer';
import { Sequelize, Table, Model, Column, IsEmail } from 'sequelize-typescript';

@Table
class User extends Model<User> {
  @Column
  name: string;
  @IsEmail
  @Column
  email: string;
}

const sequelize = new Sequelize({
  database: 'some_db',
  dialect: 'sqlite',
  username: 'root',
  password: '',
  storage: ':memory:',
});
sequelize.addModels([User]);

sequelize.sync({force: true}).then(() => {
  const data = {
    name: 'Name',
    email: 'email@example.com'
  };
  const user = plainToClass(User, data);
  const plain = classToPlain(user);
});
```
the received error is:
```
TypeError: Class constructor User cannot be invoked without 'new'
    at _loop_1 (/home/sami/Development/express-ts/src/TransformOperationExecutor.ts:150:47)
    at TransformOperationExecutor.transform (/home/sami/Development/express-ts/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at _loop_1 (/home/sami/Development/express-ts/src/TransformOperationExecutor.ts:224:43)
    at TransformOperationExecutor.transform (/home/sami/Development/express-ts/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at _loop_1 (/home/sami/Development/express-ts/src/TransformOperationExecutor.ts:224:43)
    at TransformOperationExecutor.transform (/home/sami/Development/express-ts/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at _loop_1 (/home/sami/Development/express-ts/src/TransformOperationExecutor.ts:224:43)
    at TransformOperationExecutor.transform (/home/sami/Development/express-ts/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at _loop_1 (/home/sami/Development/express-ts/src/TransformOperationExecutor.ts:224:43)
    at TransformOperationExecutor.transform (/home/sami/Development/express-ts/node_modules/class-transformer/TransformOperationExecutor.js:240:17)
    at ClassTransformer.classToPlain (/home/sami/Development/express-ts/src/ClassTransformer.ts:21:25)
    at Object.classToPlain (/home/sami/Development/express-ts/src/index.ts:17:29)
    at sequelize.sync.then (/home/sami/Development/express-ts/app.ts:29:17)
    at tryCatcher (/home/sami/Development/express-ts/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/sami/Development/express-ts/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/sami/Development/express-ts/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/sami/Development/express-ts/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/sami/Development/express-ts/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/sami/Development/express-ts/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/sami/Development/express-ts/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/sami/Development/express-ts/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/sami/Development/express-ts/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by alexpls** [comment] 2019-04-17 23:21
This appears to be a common issue with `sequelize-typescript`. I recommend checking the issues already opened about this here: https://github.com/RobinBuschmann/sequelize-typescript/issues?utf8=%E2%9C%93&q=Class+constructor+Model+cannot+be+invoked+without+%27new%27

**Comment by SamiSammour** [comment] 2019-04-21 12:22
I'm still getting the same error after reading all the answers and trying all solutions mentioned in those questions.

**Comment by alexpls** [comment] 2019-04-23 00:53
Hey @SamiSammour, you're right, this looks like an incompatibility between `sequelize` and `class-transformer`. 

Looks like this has been captured in `sequelize`'s issues here: https://github.com/RobinBuschmann/sequelize-typescript/issues/123#issuecomment-328643178.

I reckon it would be worth looking into modifying `class-transformer` so it works with `sequelize`. I could do this, but am hesitant to raise a PR since there haven't been any merged in this repo since for a few months now.

**Comment by SamiSammour** [comment] 2019-08-05 06:40
Any updates on this? it's been more than 4 months now

**Comment by LeandroFontellas** [comment] 2021-02-17 16:38
> Any updates on this? it's been more than 4 months now

Hey buddy i had a similar problem and i solved it by adding "target":"es6" on the tsconfig.json, maybe it will help you hopefully.
![image](https://user-images.githubusercontent.com/50136672/108236156-5775d200-7125-11eb-8602-921bed995246.png)

**Comment by NoNameProvided** [comment] 2021-02-22 03:49
I think this issue is not present in the current release. Can someone check, please?

**Comment by NoNameProvided** [comment] 2021-02-22 04:09
Closing as duplicate of #596.

**Closed by NoNameProvided** 2021-02-22 04:09 UTC
Labels: status: duplicate, type: fix
