### ISSUE TITLE
fix: Documentation in index.d.ts deprecated functions deserialize, serialize

### ISSUE THREAD

**Issue by gomixx18** [typestack/class-transformer#1172] opened 2022-04-22 08:23 UTC
### Description
deserialize and serialize functions have an error in documentation requesting to change the function to instanceToClass function which is not defined in the index.d.ts file.
```
export declare function serialize<T>(object: T, options?: ClassTransformOptions): string;
export declare function serialize<T>(object: T[], options?: ClassTransformOptions): string;
/**
 * Deserializes given JSON string to a object of the given class.
 *
 * @deprecated This function is being removed. Please use the following instead:
 * ```
 * **instanceToClass**(cls, JSON.parse(json), options)
 * ```
 */
export declare function deserialize<T>(cls: ClassConstructor<T>, json: string, options?: ClassTransformOptions): T;
/**
 * Deserializes given JSON string to an array of objects of the given class.
 *
 * @deprecated This function is being removed. Please use the following instead:
 * ```
 * JSON.parse(json).map(value => **instanceToClass**(cls, value, options))
 * ```
 *
 */

```
not sure what the correct wording is.

**Comment by dessalines** [comment] 2022-06-12 17:21
I'm also seeing this.

**Comment by l0ner** [comment] 2022-11-01 10:40
I have the same problem:

Steps to reproduce:

1. Install `class-transformer`
2. Try to use it

   ```TypeScript
   import { deserializeArray, deserialize } from 'class-transformer';

   class AClass
   {
   	foo: number = 1;
   	bar: string = "baz";
   }

   const jsonArrayString: string = '[{"foo": 1, "bar": "baz"}, {"foo": 2, "bar": "qux"}]';
   const deserializedArray: AClass[] = deserializeArray(AClass, jsonArrayString);

   const jsonObjectString: string = '{"foo": 3, "bar": "bax"}';
   const deserialized = deserialize(AClass, jsonObjectString);

   ```

Both functions will be reported as deprecated:

![obraz](https://user-images.githubusercontent.com/1283815/199216090-0027e63c-d19c-4d23-82c1-b732d74fc1b6.png)

![obraz](https://user-images.githubusercontent.com/1283815/199216163-8b668ebb-bd24-459e-8790-a13d2c7ec502.png)

In fact when searching for 'instanceToClass' inside the codebase, only two occurrences can be found, in the JSdoc comments of `deserialize()` and `deserializeArray()` in `src/index.ts`:

![obraz](https://user-images.githubusercontent.com/1283815/199215205-2366fac8-f894-4976-8419-a6e830fcd371.png)

Also, since the two functions are deprecated, consider removing them from the readme.

**Comment by diffy0712** [comment] 2024-05-09 21:15
Duplicate of https://github.com/typestack/class-transformer/issues/1019

**Closed as not planned by diffy0712** 2024-05-09 21:15 UTC
Labels: status: duplicate
