### ISSUE TITLE
Bug - @Expose options `toClassOnly` and `toPlainOnly` are not respected

### ISSUE THREAD

**Issue by codyburrito** [typestack/class-transformer#1351] opened 2022-09-30 20:09 UTC
```ts
interface User {
  @Expose({ name: 'sub', toClassOnly: true })
  id: string;
 
  @Expose({ name: 'first_name'})
  firstName: string;
}

const obj = { sub: '1234', first_name: 'bob'  };

const userInstance = plainToInstance(User, obj); // User { id: '1234', firstName: 'bob' }

const userPlain = instanceToPlain(userInstance); // { sub: '1234', first_name: 'bob' }

expect(userPlain).toEqual({ id: '1234', first_name: 'bob' })
```

Here is the possible place that the logic for these flags needs to be included

Relevant lines:
https://github.com/typestack/class-transformer/blob/2b100a6866b778fd7f44779ff63a95cb95f4e4c4/src/TransformOperationExecutor.ts#L175

**Comment by pavelefimenko95** [comment] 2024-01-11 18:05
any updates?

**Comment by diffy0712** [comment] 2024-05-05 11:59
Duplicate of https://github.com/typestack/class-transformer/issues/1324

**Closed as not planned by diffy0712** 2024-05-05 11:59 UTC
Labels: status: duplicate
