### ISSUE TITLE
issue: Not able generate instance if one of property is "Buffer" 

### ISSUE THREAD

**Issue by bhavink25** [typestack/class-transformer#1579] opened 2023-07-28 22:15 UTC
### Description

Below Json object trying to convert solid class but it is failing, if I am using code as Buffer.

Method : plainToInstance
GBX_6.6.108.js:6  ERROR Error: Uncaught (in promise): TypeError: Right-hand side of 'instanceof' is not callable
TypeError: Right-hand side of 'instanceof' is not callable

Everything else working great only if I use Code as buffer

{
  "id": "1",
  
  "itemType": "package",
  "name": "test",
  "description": "test",
  "status": "Draft",
  "version": "0.0.5",

  "attributes": [
   

    {
     ###  "code": "Buffer",
      "name": "Buffer %",
      "description": "Buffer%",
      "categories": [
        "Core"
        
      ],
      "displayGroup": "*",
      "group": "testGroup",
      "type": "LOV",
      "itemType": "package",
      "uom": "N/A",
      "values": [
        {
          "code": "25",
          "name": "25",
          "description": "25%",
          "isDefault": 1,
          "sequence": 1,
         
        }
      ],
      "valueStr": "25%",
      "isMultiSelect": false,
      "domains": "Domain1",
    
      "displayGroupExt": "*",
      "sequence": 3,
      "defaultValue": "25",
      "displaydelete": true,
      "displayedit": true,
      "displayview": false
    }
  ]
  
  
}
```
converted object
like 
export class IpackFull {
  @Expose() public id: string
  @Expose() public itemType: string
  @Expose() public name: string
  @Expose() public description: string
  @Expose() public status: string
  @Expose() public version: string
@Type(() => Attribute)
  public attributes: Attribute[]
}
export class Attribute {
@Expose() public code: string
  @Expose() public name: string
  @Expose() public displayGroup?: string
  @Expose() public displayGroupExt: string
  @Expose() public isHidden: boolean
  @Expose() public isDisabled: boolean
  @Expose() public sequence: number
}

**Comment by diffy0712** [comment] 2024-05-09 20:31
Closing as invalid. I was unable to reproduce the error from the code provided.
If you can add a detailed way to reproduce the error, feel free to comment on this issue.

**Closed as not planned by diffy0712** 2024-05-09 20:31 UTC
Labels: type: fix, status: cannot reproduce
