### ISSUE TITLE
Property default values are ignored on plainToClass

### ISSUE THREAD

**Issue by pedrolcn** [typestack/class-transformer#310] opened 2019-11-11 13:19 UTC
## Reproduction repo
[here](https://github.com/pedrolcn/class-transformer-default-value-issue-reproduction)

## The issue
When defining a default value for a property using the syntax
```typescript
class MyClass {
    @Expose()
    public name: string;

    @Expose()
    public active: boolean = true
}
```
if we were to call `plainToClass` the default value for `active` would be ignored.
```typescript
plainToClass(MyClass, { name: 'John Doe' })
// MyClass { name: "John Doe", active: undefined }
```

A way to remediate this is to call `classToClass` on a newly created instance of the class:
```typescript
class MyClass {
    @Expose()
    public name: string;

    @Expose()
    public active: boolean = true;

    constrtuctor(data: any) {
        Object.assing(this, data);
    }
}

classToClass(new MyClass({ name: "John Doe"} )))
// MyClass { name: "John Doe", active: true }
```

It may not be possible to detect that a property has a default value, since the transpiled code does not define any metadata for the default value, how the typescript transpiler handles this is it simply places the default assignment operation before the rest of the body of the constructor is called, eg.

```javascript
class MyClass {
    constructor(data) {
        this.active = true;

        // First it does the default assignments then it calls the constructor as defined in the.ts source
        Object.assign(this.data);
    }
}
```

## Proposed solution
Add a new decorator `@Default(val: any)` allowing to define a default value for the field which is to be assigned in case no value is passed for the decorated property when calling plainToClass

Would like to hear comments on this, as soon as we settle on an appropriate solution I can submit a PR implementing it.

**Comment by jbjhjm** [comment] 2020-01-28 15:59
This issue is known for some time now, see https://github.com/typestack/class-transformer/issues/129
As described in https://github.com/typestack/class-transformer/issues/129#issuecomment-425843700 there's a workaround using a custom decorator wrapping the Transform decorator with some configuration. No official fix by now, unfortunately.

**Comment by marcj** [comment] 2020-02-03 02:41
This is supported out of the box in [Marshal.ts](https://github.com/marcj/marshal.ts). Class-transformer is dead, time to switch.

**Comment by NoNameProvided** [comment] 2020-08-02 22:19
Duplicate of #129. This has been landed and will be released in the next version.

**Closed by NoNameProvided** 2020-08-02 22:19 UTC
Labels: status: duplicate
