### ISSUE TITLE
Date Nullable

### ISSUE THREAD

**Issue by colbeaf** [typestack/class-transformer#27] opened 2016-10-28 07:10 UTC
Hello,
the plainToClass doesnt not seams to deals with nullable Date:

Example  : 

```
@Type(() => Date)
public Act_Date_Reunion_Exp: Date;
```

=> if jsonObject Act_Date_Reunion_Exp is null , set classObject to "1970-01-01 01:00:00.000" Date

Example 2 : 

```
// no typing @Type(() => Date)
public Act_Date_Reunion_Exp: Date;
```

=> if jsonObject Act_Date_Reunion_Exp is null , set classObject to new Date() Date

Example 3

```
 @Transform(value =>moment(value), { toClassOnly: false })
 public Act_Date_Reunion_Exp: Moment;
=>throw error : target.prototype in findMetadatas() , target is null
```

Maybe i'm not doing this right 
Any Ideas ?

**Comment by artemln** [comment] 2016-12-08 10:49
@colbeaf Helllo, maybe use this:

```
@Transform(value =>moment(value).isValid() ? moment(value).isValid() : null, { toClassOnly: false })
 public Act_Date_Reunion_Exp?: Moment;
```

**Comment by tilowestermann** [comment] 2018-04-13 12:04
@artemln I suppose your solution should look like this:

```
@Transform(value =>moment(value).isValid() ? moment(value) : null, { toClassOnly: false })
 public Act_Date_Reunion_Exp?: Moment;
```

**Comment by NoNameProvided** [comment] 2018-10-24 13:04
Hi @colbeaf! 

The `@Type` operator is for user defined classes. You dont need to specify them for builtins.

I cannot reproduce your issue, I have tried with the following code: 

```ts
import { Type, plainToClass } from 'class-transformer';

class Example {
  public date: Date;
}

plainToClass(Example, { date: null });
```

This will result in the expected `Example {date: null}` object.

If you need data validation you should take a look at [typestack/class-validator][1].

I will go ahead and close this, if you have any more question regarding the topic, please feel free to continue the discussion.

[1]: https://github.com/typestack/class-validator

**Closed by NoNameProvided** 2018-10-24 13:04 UTC
Labels: status: cannot reproduce
