### ISSUE TITLE
fix: map values are undefined when transforming a map

### ISSUE THREAD

**Issue by zanminkian** [typestack/class-transformer#1297] opened 2022-08-09 07:32 UTC
### Description

**Minimal code-snippet showcasing the problem**
envs
```
"class-transformer": "^0.5.1",
"reflect-metadata": "^0.1.13",
"typescript": "^4.6.3",
"ts-node": "^10.9.1",
```

tsconfig.json
```json
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es2017",
    "lib": ["es2017"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {
      "*": ["typings/*"]
    },
    "types": ["node", "jest"],
    "resolveJsonModule": true,
    "allowJs": false,
    "declaration": true,
    "outDir": "dist",
    "removeComments": false,
    "inlineSourceMap": true,
    "isolatedModules": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictBindCallApply": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "useUnknownInCatchVariables": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "skipDefaultLibCheck": false,
    "skipLibCheck": true,
    "exactOptionalPropertyTypes": true,
    "noUncheckedIndexedAccess": true
  }
}

```

 

test.ts
```ts
import 'reflect-metadata'
import { plainToClass, Type } from 'class-transformer';

class Outer {
    @Type(()=> String)
    inner?: Map<string,string>
    otherKey?: string
}

const src = {
    inner: new Map([['k1', 'v1']]),
    otherKey: 'hello'
}
const result = plainToClass(Outer, src)
console.log(result);
```
reproduce:
```bash
ts-node test.ts
```

### Expected behavior

print
```
Outer { inner: Map(1) { 'k1' => 'v1' }, otherKey: 'hello' }
```

### Actual behavior

print
```
Outer { inner: Map(1) { 'k1' => undefined }, otherKey: 'hello' }
```

**Comment by victor-shelepen** [comment] 2023-08-18 14:23
It seems the functionality that is described here is not supported. There is a comment with a workaround solution. [Nested map?](https://github.com/typestack/class-transformer/issues/1364#issuecomment-1683991877)

**Comment by diffy0712** [comment] 2024-05-22 21:40
Duplicate of https://github.com/typestack/class-transformer/issues/1256.

**Closed as not planned by diffy0712** 2024-05-22 21:40 UTC
Labels: type: fix, status: duplicate
