### ISSUE TITLE
Expose Decorator in typescript 5.0.4

### ISSUE THREAD

**Issue by JoseLuiz432** [typestack/class-transformer#1510] opened 2023-04-20 18:27 UTC
### Description

Unable to resolve signature of method decorator when called as an expression.
  Argument of type 'ClassGetterDecoratorContext<Company, string> & { name: "cnpj"; private: false; static: false; }' is not assignable to parameter of type 'string | symbol'.

**Minimal code-snippet showcasing the problem**
 

```ts

import { Expose } from 'class-transformer';

export class Company {
  private _cnpj: string;

  constructor(cnpj: string) {
    this._cnpj = cnpj;
  }

  @Expose()
  get cnpj(): string {
    return this._cnpj;
  }
}
```

### Actual behavior

This code give to me an error: Unable to resolve signature of method decorator when called as an expression.
  Argument of type 'ClassGetterDecoratorContext<Company, string> & { name: "cnpj"; private: false; static: false; }' is not assignable to parameter of type 'string | symbol'.(1241)

**Comment by bdarcus** [comment] 2023-04-29 16:12
I'm not sure if this is related, but a few days ago, I was able to get [this](https://github.com/bdarcus/csl-next.js/blob/099dda8cd27a8bc0863cc22d3adff2272bfd4103/src/reference.ts#L45) to work, but I now get a similar `ts1240` error.

https://github.com/bdarcus/csl-next.js/pull/59

**Comment by diffy0712** [comment] 2024-05-21 19:54
Closing as invalid. I was unable to reproduce the error from the code provided.
If you can add a detailed way to reproduce the error, feel free to comment on this issue.

**Closed as not planned by diffy0712** 2024-05-21 19:54 UTC
Labels: type: fix, status: invalid, status: needs triage
