### ISSUE TITLE
fix: ObjectID changes per serialization.

### ISSUE THREAD

**Issue by iteratelance** [typestack/class-transformer#484] opened 2020-09-21 11:52 UTC
### Description
When trying to serialize a mongo ObjectId the plainToClass transformer creates a new ObjectId per instance and when using the @Transform decoration value is not the value that was passed in.

I'm using Typegoose for NestJs

For example:
```js
export class DbModelUser {
  @prop()
  _id: Schema.Types.ObjectId;

  @prop()
  first_name: string;
}
```

Assuming we have a record as follows
```js
{
    _id: 5e8b049605040a5b3a497f4b
    first_name: "Brad"
}
```

I have tried the following all with the same results.
```js
export class UserResponse {
  @Type(() => Mongoose.Types.ObjectId)
  @Expose()
  _id: Mongoose.Types.ObjectId;

  @Expose()
  first_name: string;
}

export class UserResponse {
  @Expose()
  _id: string;

  @Expose()
  first_name: string;
}
```
As a workaround the following worked but when I started using nested objects like user.profile_id where profile_id is an ObjectId I ran into the same issue and transforming every ObjectId is unwieldily. 
```js
export class UserResponse {
  @Transform((value, obj, type) => {
    if(obj._id && typeof obj._id.toString === "function"){
      return obj._id.toString();
    } else {
      return value;
    }
  })
  @Expose()
  _id: string;

  @Expose()
  first_name: string;
}
```

### Expected behavior
const data = plainToClass(UserResponse, {
    _id: 5e8b049605040a5b3a497f4b,
    first_name: "Brad"
})
```js
{
    _id: 5e8b049605040a5b3a497f4b,
    first_name: "Brad"
}
```
### Actual behavior
```js
{
    _id: someSequentialHex,
    first_name: "Brad"
}
```

Looking through the built js code in TransformOperationExecutor.js on line 132 I see this
```js
            if (!source &&
                (this.transformationType === enums_1.TransformationType.PLAIN_TO_CLASS ||
                    this.transformationType === enums_1.TransformationType.CLASS_TO_CLASS)) {
                if (isMap) {
                    newValue = new Map();
                }
                else if (targetType) {
                    newValue = new targetType();
                }
                else {
                    newValue = {};
                }
            }
```

I modified that to be the following and it seems to solve the issue. Note, `new targetType()` this seems to be the culprit.
```js
            if (!source &&
                (this.transformationType === enums_1.TransformationType.PLAIN_TO_CLASS ||
                    this.transformationType === enums_1.TransformationType.CLASS_TO_CLASS)) {
                if (isMap) {
                    newValue = new Map();
                } // check for object type ObjectID 
                else if(typeof targetType == 'function' && targetType.name == 'ObjectID'){
                    newValue = value;
                }
                else if (targetType) {
                    newValue = new targetType();
                }
                else {
                    newValue = {};
                }
            }
```

**Comment by Natashkinsasha** [comment] 2020-09-22 13:09
I have similar problem when use option "excludeExtraneousValues"

**Comment by Roms1383** [comment] 2020-10-20 09:18
I think this is related to #494, please have a look at my [comment](https://github.com/typestack/class-transformer/issues/494#issuecomment-712707954) 🙂

**Comment by iteratelance** [comment] 2020-10-20 10:44
@Roms1383 yes I think you're correct.  The serialization code seems to instantiate a new ObjectId regardless.

**Comment by Rush** [comment] 2021-01-07 02:28
Just found this issue the hard way. Wasted 2 hours. ;)

**Comment by Rush** [comment] 2021-01-07 04:15
Create w new `ExposeId` decorator to workaround this problem:
```
export const ExposeId = (options?: ExposeOptions) =>
  ((target: Object, propertyKey: string) =>  {
    Transform((_, obj) => obj[propertyKey])(target, propertyKey);
  });
```

Usage:
```
@Schema()
class Cat {
  @ExposeId()
  _id: Types.ObjectId;
}
```

**Comment by NoNameProvided** [comment] 2021-01-14 16:03
Closing as a duplicate of #494. The linked answer by @Roms1383 is the correct way to work around this. For class-transformer this is the expected behavior. We will discuss how to document this in the other issue.

**Closed by NoNameProvided** 2021-01-14 16:03 UTC
Labels: status: duplicate, type: question
