### ISSUE TITLE
question: why does @Type(() => Boolean) always return true?

### ISSUE THREAD

**Issue by Pacheco95** [typestack/class-transformer#676] opened 2021-03-31 18:06 UTC
**I was trying to...**
Parse an NestJs http request params to a filter class but the property I'm filtering is a boolean which is always being converted to true.

**The problem:**
Nest will parse the query params to an object whose properties keys are the same passed to the browser but the values are all converted to strings. So the object taken by `class-transformer` is something like this:

URL: http://example.com/?clt=something

```json
{
  "clt": "something"
}
```
And I need to convert this stringified object to my filter class:

```ts
import { IsBoolean } from 'class-validator';
import { Expose, Type } from 'class-transformer';

export class EmployeeFilter {
  @Expose()
  @IsBoolean()
  @Type(() => Boolean)
  clt?: boolean
}
```
If I pass false to the url, the parsed object still with `clt=true`

Am I missing something?

Doc: https://github.com/typestack/class-transformer#working-with-nested-objects
Codesandbox https://codesandbox.io/s/nestjs-forked-4x3qd?file=/src/validation.pipe.ts

**Comment by alereca** [comment] 2021-04-19 18:55
Hi @Pacheco95, you might try using ```@Transform()``` class-transformer decorator. In this case, you could pass an arrow function that maps an input string to a valid type like this: 
```javascript
Transform(({ value }) => optionalBooleanMapper.get(value))
```
```javascript
const optionalBooleanMapper = new Map([
  ['undefined', undefined],
  ['true', true],
  ['false', false],
]);
```
In order to avoid having all that boilerplate in your dtos, I would recommend creating a custom decorator (it's just a very simple function), for example:
```javascript
export const ParseOptionalBoolean = () =>
  Transform(({ value }) => optionalBooleanMapper.get(value));
```

**Comment by Pacheco95** [comment] 2021-04-19 19:31
Nice tip! I'll do it. Thank you!

**Comment by diffy0712** [comment] 2024-05-15 19:58
Duplicate of https://github.com/typestack/class-transformer/issues/550

**Closed by diffy0712** 2024-05-15 19:58 UTC
Labels: type: question
