### ISSUE TITLE
incorrect dependency handling

### ISSUE THREAD

**Issue by AntonPilyak** [typestack/class-transformer#171] opened 2018-08-30 09:40 UTC
Quote from the documentation: " reflect-metadata shim is required, install it too:
npm install reflect-metadata --save
and make sure to import it in a global place, like app.ts:
import "reflect-metadata";
" - that seems to be incorrect dependencies handling. It would be much more convenient to let npm doing this instead of developers. global dependencies sometimes is not the best thing as well.

**Comment by cojack** [comment] 2018-10-21 11:58
I can agree with you @AntonPilyak , that `reflect-metadata` should be in the `dependencies` list, but I don't know for what sake is putting `import "reflect-metadata";` at the top of the project files. Can any one explain that for me? Because I'm using `class-transformer` for few months, and doesn't have any problems without this part in my projects.

**Comment by MTschannett** [comment] 2018-10-22 20:01
I gues this is needed because Reflect is used without an import.

I seen this in decorator.ts (sorry I cannot pin the line on my mobile)

I don't know if it could be imported with something like 

```
import {Reflect} from 'reflect-metadata'
``` 

at the top of the file.

**Comment by MTschannett** [comment] 2018-10-22 20:11
From the docs i don't see a reason why couldn't import it like this were we need it. 

[Docs](https://github.com/rbuckton/reflect-metadata/blob/master/README.md)

**Comment by MTschannett** [comment] 2018-10-23 17:28
ok . I investigated this a little bit more. 

I was wrong. Reflect metadata has to be imported from a global place. There are two libraries that offer a implementation for this. The npm package [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) and [core-js](https://github.com/zloirock/core-js#ecmascript-reflect).

The first is mentioned on the typescript documentation page. The second one is used by angular.

When creating an angular project meta-data is imported by default.

@cojack Do you use a core-js implementation?

**Comment by NoNameProvided** [comment] 2018-10-24 12:31
This is by design, and there are multiple reasons.

First and most important is that `reflect-metadata` is a shim and we don't know if your runtime has it or not (currently it does not for sure) and even if your system supports it's natively we don't know if you want to use the native or the shim version. If we inject it by default, we add the chance of breaking all older version of this lib in runtimes where reflect-metadata is natively supported. 

Second, it is used by multiple projects (eg: class-validator, class-transformer, routing-controllers, TypeORM, Angular) if we pin and provide the dependency in one of these libs, then the other libs will have no choice but to use the same version. 

So we leave this choice to the developer. 

I will go ahead and close this, feel free to continue the discussion if you have any more question.

**Closed by NoNameProvided** 2018-10-24 12:31 UTC
Labels: status: wontfix, type: docs, type: question
