### ISSUE TITLE
When utilizing @Type discriminator with multiple types on ClassToplain value is altered

### ISSUE THREAD

**Issue by galwa** [typestack/class-transformer#775] opened 2021-06-08 14:40 UTC
When utilizing @Type discriminator with multiple name / values were some of the values are Shared
For Example :

`    @Type(() => Object, {
        keepDiscriminatorProperty: true,
        discriminator: {
            property: 'type',
            subTypes: [
                { value: ClassA, name: 'A' }
                , { value: ClassA, name: 'B'}
                , { value: ClassA, name: 'C'}
                , { value: ClassB, name: 'D'}
                , { value: ClassB, name: 'E'}
                , { value: ClassB, name: 'F'}
                , { value: ClassB, name: 'G'}
            ]
        }
    })`

On ClassToPlain value is altered 

### Expected behavior
discriminator field Value should not change 

### Actual behavior
On TransformOperationExecutor.ts line 71 :
`
if (this.transformationType === TransformationType.CLASS_TO_PLAIN) {              subValue[targetType.options.discriminator.property] = targetType.options.discriminator.subTypes.find(                subType =&gt; subType.value === subValue.constructor              ).name;            }
`
If for example 'type' field is equal to 'B' after ClassToPlain it would change to 'A' as its value is updated based on the constructor type

**Comment by diffy0712** [comment] 2024-05-15 19:28
Closing as invalid. I was unable to reproduce the error from the code provided.
If you can add a detailed way to reproduce the error, feel free to comment on this issue.

**Closed by diffy0712** 2024-05-15 19:28 UTC
Labels: type: fix, status: needs triage
