### ISSUE TITLE
fix: plainToClass method missing in Type definition

### ISSUE THREAD

**Issue by ghost** [typestack/class-transformer#994] opened 2021-11-20 17:05 UTC
### Description

Seems like the plainToClass type definition is missing in version 0.5.0

**Minimal code-snippet showcasing the problem**
 

```ts
/**
 * Converts plain (literal) object to class (constructor) object. Also works with arrays.
 */
export declare function plainToClass<T, V>(cls: ClassConstructor<T>, plain: V[], options?: ClassTransformOptions): T[];
export declare function plainToClass<T, V>(cls: ClassConstructor<T>, plain: V, options?: ClassTransformOptions): T;
```

### Expected behavior

Expected type definition for plainToClass method like version 0.4.0

### Actual behavior

No type definition for plainToClass method.

**Comment by c43721** [comment] 2021-11-20 19:55
This is working as intended, see breaking changes in https://github.com/typestack/class-transformer/blob/develop/CHANGELOG.md.

Basically, they changed the names of those methods. You should use the new methods now instead.

**Comment by c43721** [comment] 2021-11-22 19:47
@ghost fixed in https://github.com/typestack/class-transformer/commit/9c9012f1bfe720d5f0d5252e93b331aaf5fe9e4e (#1003)

**Closed** 2024-05-14 22:06 UTC
Labels: type: fix, status: needs triage
