### ISSUE TITLE
Exclude decorator not works with Nestjs and Typeorm entities

### ISSUE THREAD

**Issue by MarcoLopes389** [typestack/class-transformer#1539] opened 2023-05-22 20:07 UTC
### Description
I have an typeorm entity and I added the Exclude decorator on a property, like this:

```typescript
@Entity()
export class Profile {
  @ApiProperty()
  @PrimaryGeneratedColumn()
  id: number;

  @ApiProperty()
  @Column()
  name: string;

  @Exclude()
  @ApiProperty()
  @OneToOne(() => User)
  user: User;
}
```

In my main.ts file I called the ClassSerializerInterceptor:

```typescript
const app = await NestFactory.create(AppModule);
app.useGlobalPipes(new ValidationPipe());
app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));
```

### Expected behavior
I expected the user not comes in http response

### Actual behavior
The user comes and shows the user password. It is encrypted, but I don't need this property

@nestjs/common version: 9.0.0
class-transformer version: 0.5.1

**Comment by yaoyonstudio** [comment] 2023-07-15 11:09
Did you use @Res() in your profileController? (something like res.json(profile))

Just return the pure profile data without @Res().

**Comment by MarcoLopes389** [comment] 2023-07-18 03:01
No, i didn't. I returned the pure data.

**Comment by yaoyonstudio** [comment] 2023-07-27 08:23
main.ts
```
  // validation pipe
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));
  app.useGlobalInterceptors(new ClassSerializerInterceptor(app.get(Reflector)));
```



account.controller.ts
```
@Get('profile')
  @ApiOperation({ summary: 'get account profile' })
  @ApiCommonResponse(OmitType(Account, ['password']))
  async profile(@Req() req) {
    const result = await this.accountService.findById(req.user.id);
    if (!result) {
      throw new EntityNotFoundError(Account, 'id');
    }
    return result;
  }
```



account.entity.ts
```
  @ApiProperty({ type: String })
  @Column()
  @Exclude({ toPlainOnly: true })
  password: string;

```

Here's my working example.

**Comment by diffy0712** [comment] 2024-05-09 19:38
Hello @MarcoLopes389,

if this issue is still relevant and unsolved on your side, could you please provide a bit more information?
From this example I cannot reproduce your error, because I would need to set up nestjs with typeorm just for this.
If you could provide the plain object at least, it would help.

If you could solve it or not relevant anymore, please close this issue.

**Comment by diffy0712** [comment] 2024-05-18 09:45
The issue does not contain a simple reproduction case.

Closing as invalid.

**Closed as not planned by diffy0712** 2024-05-18 09:45 UTC
Labels: type: fix, status: needs triage
