### ISSUE TITLE
plainToClass 2 overloads with same parameters confuse the IDE

### ISSUE THREAD

**Issue by rmindel** [typestack/class-transformer#119] opened 2018-01-01 11:45 UTC
I am using Visual Studio Code and angular 4 (typescript 2)

When using plainToClass like this:
`var res = plainToClass(Models.Model, modelData)`
The IDE thinks the return value is Models.Model[], it will not compile as I am using it as a singular Models.Model. 
`modelArray.push(res)`

The workaround I found for this issue is using it like this:
`plainToClass<Models.Model,object>(Models.Model, modelData)`

This way I let the compiler know the V is a singular and not an Array and catch the right overload.

It just makes this code almost twice the size and not as nice to look at as you intended.

**Comment by sebastian-zarzycki-es** [comment] 2018-02-21 12:52
Use:
plainToClass(Models.Model, modelData as Object)
plainToClass(Models.Model, modelData as Object[])

to force proper signature detection. A little bit nicer syntax.

**Comment by lucasklaassen** [comment] 2018-06-11 23:59
@sebastian-zarzycki-es thanks for this, we should look at adding this to the main README.md

**Comment by NoNameProvided** [comment] 2018-10-26 16:40
Thanks for the report, we can fix this probably with the tuning of the function overload declarations.

**Comment by NoNameProvided** [comment] 2020-08-02 22:56
Duplicate of #30. This is fixed.

**Closed by NoNameProvided** 2020-08-02 22:56 UTC
Labels: comp: core, status: duplicate, type: fix
