### ISSUE TITLE
fix: plainToInstance overwrites constructor for immutable.js `List`

### ISSUE THREAD

**Issue by flylo** [typestack/class-transformer#1563] opened 2023-07-08 18:49 UTC
### Description
Passing an immutable.js `List` into `plainToInstance` somehow overwrites [this value](https://github.com/immutable-js/immutable-js/blob/41fcd04a1e02f9914e9304da316592ac2c83c7ed/src/List.js#L408), thereby making all calls to the `List()` function return a list with extra elements. I know this repo seems un-maintained at this time, but I figured I'd put this here in-case anyone else runs into this behavior. It's a pretty nasty one to debug.

**Minimal code-snippet showcasing the problem**
```json
"class-transformer": "0.5.1",
"immutable": "^4.3.0",
"jest": "^29.5.0",
"ts-jest": "^29.1.0",
```
```ts
import { instanceToPlain, plainToInstance } from "class-transformer";
import { List } from "immutable";

class Something {
  constructor(public foo: List<string>) {}
}

describe("lol", () => {
  it("should work", function () {
    const thing = List.of("hi");
    const result = plainToInstance(Something, {
      foo: thing
    });
    expect(result.foo).toEqual(thing);
    console.log(List().toJSON());
    expect(List().size).toEqual(0);
  });
});
```

When run, this gives us the following:

```
  console.log
    [ 'hi' ]

      at Object.<anonymous> (test/lol.spec.ts:15:13)

Error: expect(received).toEqual(expected) // deep equality

Expected: 0
Received: 1
<Click to see difference>
```

### Expected behavior
The `plainToInstance` function does not mutate functions in other libraries.

### Actual behavior
The `plainToInstance` function alters the state of `immutable.js` such that it breaks all usage of the library in the same node process. As you can see in the example above, a call to create an empty list (`List()`) returns a `List` with one element, `"hi"`.

**Comment by diffy0712** [comment] 2024-05-22 20:39
hello @flylo,

This is caused by the fact that you provide in an instance in your plain object, which currently is handled in a way that it will create a new instance from that type (your factory function in this case), furthermore, since you use the 'exposeAll' strategy(default) it will also try to transform your 'List' object as well, which will call new on some 'VNode' (which I suppose is some internal implementation of immutable). That is somehow making this 'immutable' state mutable.

This issue is basically a duplicate of https://github.com/typestack/class-transformer/issues/1648, but in a different way. 

That said, I do not really understand why you would want to use `class-transformer` if you already have the instance of your type (in your plain), why not do `new Something(thing)`?

If you would have the list in your plain in a simple array, you could do:
```typescript
class Something {
  @Expose()
  @Transform(({value}: {value: Array<string>}) => List.of(value), {toClassOnly: true})
  @Transform(({value}: {value: List<string>}) => value.toArray(), {toPlainOnly: true})
  public foo: List<string>
}

const thing = ["hi"];
const result = plainToInstance(Something, {
  foo: thing
});

```

**Comment by diffy0712** [comment] 2024-05-22 21:25
Closing in favor of https://github.com/typestack/class-transformer/issues/1443

**Closed as not planned by diffy0712** 2024-05-22 21:25 UTC
Labels: type: fix, status: needs triage
