### ISSUE TITLE
fix: global storage singleton not shared between packages

### ISSUE THREAD

**Issue by soloyal** [typestack/class-transformer#1157] opened 2022-04-06 12:24 UTC
### Description

You can't incapsulate/export your Expose,Exclude, class-transformer configuration into published package because your storage is not a global/cross package singleton.

For example: I created the private package for the company with "users/any other entity" repository. It has classes of entities with class-transformer instructions how to serialize data. 

The exact serialization I do in the project where I use "users/any other entity" repository as a dependency. So, my application has 2 class-transformer scopes with 2 different metadata storage singletons(one from the package and one from the project). Of course it can't serialize bc in the project class transformer metadata storage has no data for the classes imported from my package(it is in another class transformer metadata storage located inside the package).

### Suggestion/Solution
To fix in your **storage.ts** file add additional logic please 
```ts
const globalRef = global as any
export const defaultMetadataStorage = global.classTransformerMetadataStorage 
  || (global.classTransformerMetadataStorage = new MetadataStorage());
```
this will share metadata storage between packages

### Temporary solution
Export class-transformer in your package  and import in your project

for example: 
in your package **@private/your-package** implementation add something like
```ts
...
@Exclude()
export class EntityExampleClass {
   constructor(payload?: Partial<EntityExampleClass>) {
      Object.assign(this, payload)
   }

   @Expose({ groups: ['public', 'event'] })
    name: string
}

export * as transformer from 'class-transformer'
```

in your project use
```ts
import { transformer, EntityExampleClass } from '@private/your-package'

const { Expose, Exclude, instanceToPlain } from transformer

....api controller method
return instanceToPlain<EntityExampleClass>(new EntityExampleClass(), { groups: ['public'] })

```

**Comment by petrzjunior** [comment] 2022-04-07 15:37
Duplicate of #928

**Comment by y0gzah** [comment] 2023-02-01 19:48
This is still not fixed.
I'm using class-transformer class-validator class-sanitizier and routing-controllers in different packages of my project.
And decorators just don't exist at all from one package to the other.

**Comment by diffy0712** [comment] 2024-05-14 22:42
Duplicate of #928

**Closed as not planned by diffy0712** 2024-05-14 22:42 UTC
Labels: status: duplicate
