### ISSUE TITLE
perf: performance regression in browser

### ISSUE THREAD

**Issue by capc0** [typestack/class-transformer#309] opened 2019-11-05 15:28 UTC
I have fairly simple class definition with some nested sub-classes and array properties.

The transformation of 2.000 of those objects in one array takes about 25 seconds in the browser with plainToClass or classToPlain.
The same class definition transformed in NodeJS finishes in under 200 ms. 

Any ideas ?

Tested the browser stuff in an angular environment.

**Comment by dqueffeulouatw** [comment] 2019-11-16 21:32
I have also this problem with an Angular/typescript application which uses plainToClass from a SSE event API with min rate at 30 messages/s. The plainToClass comes high in Chrome profiler.
I'm wondering if I need to stay with Object for all the events but it's a bit of refactoring.

**Comment by capc0** [comment] 2019-11-17 09:46
Im also running in an angular/typescript environment. Either Ionic or Electron, its slow in both cases. Did not found a workaround for now...

**Comment by rightisleft** [comment] 2020-01-28 22:43
I am seeing the same thing with Angular / Typescript / Chrome - i'm able to look at slow down in the performance profiler and isolate to to t.transform via TransformOperationExecutor.js.pre-build-optimizer.js:25

**Comment by rightisleft** [comment] 2020-01-28 22:59
This is definitely a regression between 0.1.10 and 0.2.X. Downgrading restores functionality.

**Comment by marcj** [comment] 2020-02-03 02:42
Class-transformer is horrible slow thanks to its very inefficient code. [Marshal.ts](https://github.com/marcj/marshal.ts) is over 300x faster. Class-transformer is dead, time to switch.

**Comment by rightisleft** [comment] 2020-02-03 15:28
@pleerock @MichalLytek @NoNameProvided - Is this project actively maintained?

**Comment by marcj** [comment] 2020-02-03 15:39
You have to ask that? Look at the PRs, open issues, commit history. No matter what, this project is dead und unmaintained.

**Comment by MichalLytek** [comment] 2020-02-04 08:34
If you would like to help, rather than complain, write email to @pleerock, he will add you to the typestack team 😉

**Comment by marcj** [comment] 2020-02-06 00:24
@MichalLytek while I appreciate the invitation very much I have to respectfully decline due to a variety of reasons. One being that I think competition is good for everyone and another that I don't want to revive a dying project. I already did that a couple of times and it never ended good.

**Comment by rightisleft** [comment] 2020-02-07 21:39
@MichalLytek - Im just trying to sort the information on this thread - is there any information on this ticket / project? The performance regression we encountered was crippling until we downgraded.

Happy to help where I can.

**Comment by capc0** [comment] 2020-02-26 18:09
@rightisleft when i downgrade to 0.1.10 my dates are not converted from strings to date objects. you have had similiar problems?

**Comment by JulianFarhi** [comment] 2020-07-09 15:54
After investigation, the problem comes from the version 0.2.1 with the testForBuffer function (src/TransformOperationExecutor.ts, line 101).
I just made a simple by removing the condition and the function but the result was significant.

**Comment by NoNameProvided** [comment] 2020-07-29 21:48
Thanks @JulianFarhi to testing this out. I wonder how even that snippet works in the browser? `Buffer` is not an exposed object in browsers. Do you provide a shim manually?

**Comment by capc0** [comment] 2020-07-30 06:27
```console.log(Buffer)``` in my ionic/angular app, it throw a error (can´t find variable Buffer).
```console.log(Buffer)``` in my electron/angular app logs the nodeJS buffer function ```function Buffer(arg, encodingOrOffset, length)```. I wonder how the browser process has access to that function tho. Should only be available in the electron process IMO.

**Comment by NoNameProvided** [comment] 2020-07-30 08:13
I have changed the way we check for Buffers for increased speed. Will be released in the next version.

<details>
<summary>JSPerf</summary>

![performance](https://user-images.githubusercontent.com/4706265/88898435-010a7a00-d24d-11ea-8555-ebef8bce0e5e.png)


</details>

**Closed** 2020-07-30 11:36 UTC
Labels: priority: high, status: has PR, type: fix
